AllCops:
  NewCops: enable
  Exclude:
    - 'netoviz/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'yang/**/*'
    - 'public/**/*'
    - 'dist/**/*'

Layout/LineLength:
  Enabled: true
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'model_defs/**/*'

Security/Eval:
  Exclude:
    - 'model_defs/bf_trial/*.rb'

Style/OptionalBooleanParameter:
  Enabled: false # TODO: fix boolean method parameter styles.
