AllCops:
  Exclude:
    - 'netoviz/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'yang/**/*'
    - 'public/**/*'
    - 'dist/**/*'

Metrics/BlockLength:
  Exclude:
    - 'model_defs/**/*'

Security/Eval:
  Exclude:
    - 'model_defs/bf_trial/*.rb'

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
